
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 19 13:59:52 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 44;
  public static final int CONST = 23;
  public static final int CHAR = 19;
  public static final int GREATEROREQUAL = 36;
  public static final int SMALLER = 37;
  public static final int PRIVATE = 53;
  public static final int GREATER = 35;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 28;
  public static final int MODRIGHT = 50;
  public static final int FOR = 26;
  public static final int MINUS = 29;
  public static final int ADDRIGHT = 46;
  public static final int RPAREN = 7;
  public static final int AND = 39;
  public static final int SMALLEROREQUAL = 38;
  public static final int OR = 40;
  public static final int BOOL = 16;
  public static final int COMMA = 12;
  public static final int MULRIGHT = 48;
  public static final int CLASS = 21;
  public static final int INC = 41;
  public static final int DIV = 31;
  public static final int DIFFERENT = 34;
  public static final int PLUS = 10;
  public static final int IF = 17;
  public static final int ABSTRACT = 22;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 45;
  public static final int EQUAL = 8;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int NUMBER = 14;
  public static final int MOD = 32;
  public static final int BREAK = 20;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int COLON = 52;
  public static final int FOREACH = 51;
  public static final int SUBRIGHT = 47;
  public static final int SAME = 33;
  public static final int LBRACE = 3;
  public static final int ELSE = 18;
  public static final int PROTECTED = 54;
  public static final int POINT = 43;
  public static final int READ = 25;
  public static final int PUBLIC = 55;
  public static final int DIVRIGHT = 49;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 27;
  public static final int PROG = 2;
  public static final int DEC = 42;
  public static final int PRINT = 11;
}

